### PR TITLE
Fix Caps

### PR DESCRIPTION
**Pull request by Atvaster**
Git gud

### CODE REVIEW

**Comment by CodeF53** [comment]
Tooltips being all lower case was a stylistic choice

**Comment by Atvaster** [comment]
Looks wierd af

**Comment by CodeF53** [comment]
Also you missed the blog and email tooltips

**Comment by Atvaster** [comment]
First time mistakes  *shrug*

**Comment by CodeF53** [comment]
> Looks wierd af

Nah

**Pull request closed without merging**
